name: msvc-oneapi-opencoarray.yml

on:
  workflow_dispatch:
  
  

jobs:
  test-fortran-cc:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
      #ubuntu-latest, macos-latest, 
        os: [windows-2022]
        toolchain:
          - {compiler: gcc, version: 'latest'}
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel-classic, version: '2021.10'}
          - {compiler: nvidia-hpc, version: 'latest'}
          - {compiler: lfortran, version: '0.45.0'}
          - {compiler: aocc, version: '5.1.0'}
        exclude:
          - os: macos-latest
            toolchain: {compiler: intel}
          - os: macos-latest
            toolchain: {compiler: intel-classic}
          - os: macos-latest
            toolchain: {compiler: nvidia-hpc}
          - os: windows-latest
            toolchain: {compiler: nvidia-hpc}
          - os: macos-latest
            toolchain: {compiler: aocc}
          - os: windows-latest
            toolchain: {compiler: aocc}

    steps:
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - run: |
          ${{ env.FC }} ... # environment vars FC, CC, and CXX are set
          ${{ steps.setup-fortran.outputs.fc }} ... # outputs work too
          
  build-windows:
    if: true
    runs-on: windows-2022

    steps:
      - name: Configure Developer Command Prompt for MSVC
        uses: ilammy/msvc-dev-cmd@v1
        
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
          version: '2025.0'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Clone OpenCoarrays
        run: |
          git clone https://github.com/sourceryinstitute/OpenCoarrays
      
      - name: Configure and Build OpenCoarrays
        shell: cmd
        run: |
          :: Environment paths are auto-configured by the setup action!
          cd OpenCoarrays
          mkdir build
          cd build
          
          :: Configure CMake using Intel Fortran compiler (ifx)
          cmake .. -G "Visual Studio 17 2022" ^
                   -T "Intel(R) Next-Gen Fortran Compiler" ^
                   -DCMAKE_INSTALL_PREFIX="C:\OpenCoarrays"
                   
          :: Compile and install the library
          cmake --build . --config Release --target install
            

#    - name: Setup Intel Next-Gen Fortran (ifx)
#      uses: fortran-lang/setup-fortran@v1
#      with:
#        compiler: intel
#        version: '25.2' # Or a specific year/version if needed

    # (no-windows)
#    - name: Setup Intel oneAPI
#      uses: rscohn2/setup-oneapi@v0
#      with:
#        components: |
#          mkl
#          icx
#          ifx
#          impi
#        cache: true # Drastically speeds up subsequent pipeline runs

        # Official action to configure MSVC 2022 environment variables (cl, link, nmake, etc.)
  
