name: msvc-oneapi-opencoarray.yml

on:
  push:
    branches: 
      main
  workflow_dispatch:
    
  

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Install Intel oneAPI
        uses: modflowpy/install-intelfortran-action@v1
        with:
        # Options: 'compiler' (default), 'mkl', or 'hpckit'
          component: |
           hpckit 
           compiler
      - name: Configure Developer Command Prompt for MSVC
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Clone OpenCoarrays
        run: |
          git clone https://github.com/sourceryinstitute/OpenCoarrays
      
      - name: Configure and Build OpenCoarrays
        shell: cmd
        run: |
          :: Environment paths are auto-configured by the setup action!
          cd OpenCoarrays
          mkdir build
          cd build
          
          :: Configure CMake using Intel Fortran compiler (ifx)
          cmake .. -G "Visual Studio 17 2022" ^
                   -T "Intel(R) Next-Gen Fortran Compiler" ^
                   -DCMAKE_INSTALL_PREFIX="C:\OpenCoarrays"
                   
          :: Compile and install the library
          cmake --build . --config Release --target install
            

#    - name: Setup Intel Next-Gen Fortran (ifx)
#      uses: fortran-lang/setup-fortran@v1
#      with:
#        compiler: intel
#        version: '25.2' # Or a specific year/version if needed

    # (no-windows)
#    - name: Setup Intel oneAPI
#      uses: rscohn2/setup-oneapi@v0
#      with:
#        components: |
#          mkl
#          icx
#          ifx
#          impi
#        cache: true # Drastically speeds up subsequent pipeline runs

        # Official action to configure MSVC 2022 environment variables (cl, link, nmake, etc.)
  
